//! Autogenerated: 'src/ExtractionOCaml/unsaturated_solinas' --lang Rust --inline p448 64 8 '2^448 - 2^224 - 1' carry_mul carry_square carry add sub opp selectznz to_bytes from_bytes relax
//! curve description: p448
//! machine_wordsize = 64 (from "64")
//! requested operations: carry_mul, carry_square, carry, add, sub, opp, selectznz, to_bytes, from_bytes, relax
//! n = 8 (from "8")
//! s-c = 2^448 - [(2^224, 1), (1, 1)] (from "2^448 - 2^224 - 1")
//! tight_bounds_multiplier = 1 (from "")
//!
//! Computed values:
//!   carry_chain = [3, 7, 4, 0, 5, 1, 6, 2, 7, 3, 4, 0]
//!   eval z = z[0] + (z[1] << 56) + (z[2] << 112) + (z[3] << 168) + (z[4] << 224) + (z[5] << 0x118) + (z[6] << 0x150) + (z[7] << 0x188)
//!   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8)
//!   balance = [0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffc, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe]

#![allow(unused_parens)]
#![allow(non_camel_case_types)]

/** fiat_p448_u1 represents values of 1 bits, stored in one byte. */
pub type fiat_p448_u1 = u8;
/** fiat_p448_i1 represents values of 1 bits, stored in one byte. */
pub type fiat_p448_i1 = i8;
/** fiat_p448_u2 represents values of 2 bits, stored in one byte. */
pub type fiat_p448_u2 = u8;
/** fiat_p448_i2 represents values of 2 bits, stored in one byte. */
pub type fiat_p448_i2 = i8;

/** The type fiat_p448_loose_field_element is a field element with loose bounds. */
/** Bounds: [[0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p448_loose_field_element(pub [u64; 8]);

impl core::ops::Index<usize> for fiat_p448_loose_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p448_loose_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

/** The type fiat_p448_tight_field_element is a field element with tight bounds. */
/** Bounds: [[0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p448_tight_field_element(pub [u64; 8]);

impl core::ops::Index<usize> for fiat_p448_tight_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p448_tight_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}


/// The function fiat_p448_addcarryx_u56 is an addition with carry.
///
/// Postconditions:
///   out1 = (arg1 + arg2 + arg3) mod 2^56
///   out2 = ⌊(arg1 + arg2 + arg3) / 2^56⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p448_addcarryx_u56(out1: &mut u64, out2: &mut fiat_p448_u1, arg1: fiat_p448_u1, arg2: u64, arg3: u64) {
  let x1: u64 = (((arg1 as u64) + arg2) + arg3);
  let x2: u64 = (x1 & 0xffffffffffffff);
  let x3: fiat_p448_u1 = ((x1 >> 56) as fiat_p448_u1);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_p448_subborrowx_u56 is a subtraction with borrow.
///
/// Postconditions:
///   out1 = (-arg1 + arg2 + -arg3) mod 2^56
///   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^56⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p448_subborrowx_u56(out1: &mut u64, out2: &mut fiat_p448_u1, arg1: fiat_p448_u1, arg2: u64, arg3: u64) {
  let x1: i64 = ((((((arg2 as i128) - (arg1 as i128)) as i64) as i128) - (arg3 as i128)) as i64);
  let x2: fiat_p448_i1 = ((x1 >> 56) as fiat_p448_i1);
  let x3: u64 = (((x1 as i128) & (0xffffffffffffff as i128)) as u64);
  *out1 = x3;
  *out2 = (((0x0 as fiat_p448_i2) - (x2 as fiat_p448_i2)) as fiat_p448_u1);
}

/// The function fiat_p448_cmovznz_u64 is a single-word conditional move.
///
/// Postconditions:
///   out1 = (if arg1 = 0 then arg2 else arg3)
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
#[inline]
pub fn fiat_p448_cmovznz_u64(out1: &mut u64, arg1: fiat_p448_u1, arg2: u64, arg3: u64) {
  let x1: fiat_p448_u1 = (!(!arg1));
  let x2: u64 = ((((((0x0 as fiat_p448_i2) - (x1 as fiat_p448_i2)) as fiat_p448_i1) as i128) & (0xffffffffffffffff as i128)) as u64);
  let x3: u64 = ((x2 & arg3) | ((!x2) & arg2));
  *out1 = x3;
}

/// The function fiat_p448_carry_mul multiplies two field elements and reduces the result.
///
/// Postconditions:
///   eval out1 mod m = (eval arg1 * eval arg2) mod m
///
#[no_mangle]
#[inline]
pub fn rust_fiat_p448_solinas_carry_mul(out1: &mut fiat_p448_tight_field_element, arg1: &fiat_p448_loose_field_element, arg2: &fiat_p448_loose_field_element) {
  let x1: u128 = (((arg1[7]) as u128) * ((arg2[7]) as u128));
  let x2: u128 = (((arg1[7]) as u128) * ((arg2[6]) as u128));
  let x3: u128 = (((arg1[7]) as u128) * ((arg2[5]) as u128));
  let x4: u128 = (((arg1[6]) as u128) * ((arg2[7]) as u128));
  let x5: u128 = (((arg1[6]) as u128) * ((arg2[6]) as u128));
  let x6: u128 = (((arg1[5]) as u128) * ((arg2[7]) as u128));
  let x7: u128 = (((arg1[7]) as u128) * ((arg2[7]) as u128));
  let x8: u128 = (((arg1[7]) as u128) * ((arg2[6]) as u128));
  let x9: u128 = (((arg1[7]) as u128) * ((arg2[5]) as u128));
  let x10: u128 = (((arg1[6]) as u128) * ((arg2[7]) as u128));
  let x11: u128 = (((arg1[6]) as u128) * ((arg2[6]) as u128));
  let x12: u128 = (((arg1[5]) as u128) * ((arg2[7]) as u128));
  let x13: u128 = (((arg1[7]) as u128) * ((arg2[7]) as u128));
  let x14: u128 = (((arg1[7]) as u128) * ((arg2[6]) as u128));
  let x15: u128 = (((arg1[7]) as u128) * ((arg2[5]) as u128));
  let x16: u128 = (((arg1[7]) as u128) * ((arg2[4]) as u128));
  let x17: u128 = (((arg1[7]) as u128) * ((arg2[3]) as u128));
  let x18: u128 = (((arg1[7]) as u128) * ((arg2[2]) as u128));
  let x19: u128 = (((arg1[7]) as u128) * ((arg2[1]) as u128));
  let x20: u128 = (((arg1[6]) as u128) * ((arg2[7]) as u128));
  let x21: u128 = (((arg1[6]) as u128) * ((arg2[6]) as u128));
  let x22: u128 = (((arg1[6]) as u128) * ((arg2[5]) as u128));
  let x23: u128 = (((arg1[6]) as u128) * ((arg2[4]) as u128));
  let x24: u128 = (((arg1[6]) as u128) * ((arg2[3]) as u128));
  let x25: u128 = (((arg1[6]) as u128) * ((arg2[2]) as u128));
  let x26: u128 = (((arg1[5]) as u128) * ((arg2[7]) as u128));
  let x27: u128 = (((arg1[5]) as u128) * ((arg2[6]) as u128));
  let x28: u128 = (((arg1[5]) as u128) * ((arg2[5]) as u128));
  let x29: u128 = (((arg1[5]) as u128) * ((arg2[4]) as u128));
  let x30: u128 = (((arg1[5]) as u128) * ((arg2[3]) as u128));
  let x31: u128 = (((arg1[4]) as u128) * ((arg2[7]) as u128));
  let x32: u128 = (((arg1[4]) as u128) * ((arg2[6]) as u128));
  let x33: u128 = (((arg1[4]) as u128) * ((arg2[5]) as u128));
  let x34: u128 = (((arg1[4]) as u128) * ((arg2[4]) as u128));
  let x35: u128 = (((arg1[3]) as u128) * ((arg2[7]) as u128));
  let x36: u128 = (((arg1[3]) as u128) * ((arg2[6]) as u128));
  let x37: u128 = (((arg1[3]) as u128) * ((arg2[5]) as u128));
  let x38: u128 = (((arg1[2]) as u128) * ((arg2[7]) as u128));
  let x39: u128 = (((arg1[2]) as u128) * ((arg2[6]) as u128));
  let x40: u128 = (((arg1[1]) as u128) * ((arg2[7]) as u128));
  let x41: u128 = (((arg1[7]) as u128) * ((arg2[4]) as u128));
  let x42: u128 = (((arg1[7]) as u128) * ((arg2[3]) as u128));
  let x43: u128 = (((arg1[7]) as u128) * ((arg2[2]) as u128));
  let x44: u128 = (((arg1[7]) as u128) * ((arg2[1]) as u128));
  let x45: u128 = (((arg1[6]) as u128) * ((arg2[5]) as u128));
  let x46: u128 = (((arg1[6]) as u128) * ((arg2[4]) as u128));
  let x47: u128 = (((arg1[6]) as u128) * ((arg2[3]) as u128));
  let x48: u128 = (((arg1[6]) as u128) * ((arg2[2]) as u128));
  let x49: u128 = (((arg1[5]) as u128) * ((arg2[6]) as u128));
  let x50: u128 = (((arg1[5]) as u128) * ((arg2[5]) as u128));
  let x51: u128 = (((arg1[5]) as u128) * ((arg2[4]) as u128));
  let x52: u128 = (((arg1[5]) as u128) * ((arg2[3]) as u128));
  let x53: u128 = (((arg1[4]) as u128) * ((arg2[7]) as u128));
  let x54: u128 = (((arg1[4]) as u128) * ((arg2[6]) as u128));
  let x55: u128 = (((arg1[4]) as u128) * ((arg2[5]) as u128));
  let x56: u128 = (((arg1[4]) as u128) * ((arg2[4]) as u128));
  let x57: u128 = (((arg1[3]) as u128) * ((arg2[7]) as u128));
  let x58: u128 = (((arg1[3]) as u128) * ((arg2[6]) as u128));
  let x59: u128 = (((arg1[3]) as u128) * ((arg2[5]) as u128));
  let x60: u128 = (((arg1[2]) as u128) * ((arg2[7]) as u128));
  let x61: u128 = (((arg1[2]) as u128) * ((arg2[6]) as u128));
  let x62: u128 = (((arg1[1]) as u128) * ((arg2[7]) as u128));
  let x63: u128 = (((arg1[7]) as u128) * ((arg2[0]) as u128));
  let x64: u128 = (((arg1[6]) as u128) * ((arg2[1]) as u128));
  let x65: u128 = (((arg1[6]) as u128) * ((arg2[0]) as u128));
  let x66: u128 = (((arg1[5]) as u128) * ((arg2[2]) as u128));
  let x67: u128 = (((arg1[5]) as u128) * ((arg2[1]) as u128));
  let x68: u128 = (((arg1[5]) as u128) * ((arg2[0]) as u128));
  let x69: u128 = (((arg1[4]) as u128) * ((arg2[3]) as u128));
  let x70: u128 = (((arg1[4]) as u128) * ((arg2[2]) as u128));
  let x71: u128 = (((arg1[4]) as u128) * ((arg2[1]) as u128));
  let x72: u128 = (((arg1[4]) as u128) * ((arg2[0]) as u128));
  let x73: u128 = (((arg1[3]) as u128) * ((arg2[4]) as u128));
  let x74: u128 = (((arg1[3]) as u128) * ((arg2[3]) as u128));
  let x75: u128 = (((arg1[3]) as u128) * ((arg2[2]) as u128));
  let x76: u128 = (((arg1[3]) as u128) * ((arg2[1]) as u128));
  let x77: u128 = (((arg1[3]) as u128) * ((arg2[0]) as u128));
  let x78: u128 = (((arg1[2]) as u128) * ((arg2[5]) as u128));
  let x79: u128 = (((arg1[2]) as u128) * ((arg2[4]) as u128));
  let x80: u128 = (((arg1[2]) as u128) * ((arg2[3]) as u128));
  let x81: u128 = (((arg1[2]) as u128) * ((arg2[2]) as u128));
  let x82: u128 = (((arg1[2]) as u128) * ((arg2[1]) as u128));
  let x83: u128 = (((arg1[2]) as u128) * ((arg2[0]) as u128));
  let x84: u128 = (((arg1[1]) as u128) * ((arg2[6]) as u128));
  let x85: u128 = (((arg1[1]) as u128) * ((arg2[5]) as u128));
  let x86: u128 = (((arg1[1]) as u128) * ((arg2[4]) as u128));
  let x87: u128 = (((arg1[1]) as u128) * ((arg2[3]) as u128));
  let x88: u128 = (((arg1[1]) as u128) * ((arg2[2]) as u128));
  let x89: u128 = (((arg1[1]) as u128) * ((arg2[1]) as u128));
  let x90: u128 = (((arg1[1]) as u128) * ((arg2[0]) as u128));
  let x91: u128 = (((arg1[0]) as u128) * ((arg2[7]) as u128));
  let x92: u128 = (((arg1[0]) as u128) * ((arg2[6]) as u128));
  let x93: u128 = (((arg1[0]) as u128) * ((arg2[5]) as u128));
  let x94: u128 = (((arg1[0]) as u128) * ((arg2[4]) as u128));
  let x95: u128 = (((arg1[0]) as u128) * ((arg2[3]) as u128));
  let x96: u128 = (((arg1[0]) as u128) * ((arg2[2]) as u128));
  let x97: u128 = (((arg1[0]) as u128) * ((arg2[1]) as u128));
  let x98: u128 = (((arg1[0]) as u128) * ((arg2[0]) as u128));
  let x99: u128 = (x95 + (x88 + (x82 + (x77 + (x31 + (x27 + (x22 + x16)))))));
  let x100: u64 = ((x99 >> 56) as u64);
  let x101: u64 = ((x99 & (0xffffffffffffff as u128)) as u64);
  let x102: u128 = (x91 + (x84 + (x78 + (x73 + (x69 + (x66 + (x64 + (x63 + (x53 + (x49 + (x45 + x41)))))))))));
  let x103: u128 = (x92 + (x85 + (x79 + (x74 + (x70 + (x67 + (x65 + (x57 + (x54 + (x50 + (x46 + (x42 + (x13 + x7)))))))))))));
  let x104: u128 = (x93 + (x86 + (x80 + (x75 + (x71 + (x68 + (x60 + (x58 + (x55 + (x51 + (x47 + (x43 + (x20 + (x14 + (x10 + x8)))))))))))))));
  let x105: u128 = (x94 + (x87 + (x81 + (x76 + (x72 + (x62 + (x61 + (x59 + (x56 + (x52 + (x48 + (x44 + (x26 + (x21 + (x15 + (x12 + (x11 + x9)))))))))))))))));
  let x106: u128 = (x96 + (x89 + (x83 + (x35 + (x32 + (x28 + (x23 + (x17 + x1))))))));
  let x107: u128 = (x97 + (x90 + (x38 + (x36 + (x33 + (x29 + (x24 + (x18 + (x4 + x2)))))))));
  let x108: u128 = (x98 + (x40 + (x39 + (x37 + (x34 + (x30 + (x25 + (x19 + (x6 + (x5 + x3))))))))));
  let x109: u128 = ((x100 as u128) + x105);
  let x110: u64 = ((x102 >> 56) as u64);
  let x111: u64 = ((x102 & (0xffffffffffffff as u128)) as u64);
  let x112: u128 = (x109 + (x110 as u128));
  let x113: u64 = ((x112 >> 56) as u64);
  let x114: u64 = ((x112 & (0xffffffffffffff as u128)) as u64);
  let x115: u128 = (x108 + (x110 as u128));
  let x116: u128 = ((x113 as u128) + x104);
  let x117: u64 = ((x115 >> 56) as u64);
  let x118: u64 = ((x115 & (0xffffffffffffff as u128)) as u64);
  let x119: u128 = ((x117 as u128) + x107);
  let x120: u64 = ((x116 >> 56) as u64);
  let x121: u64 = ((x116 & (0xffffffffffffff as u128)) as u64);
  let x122: u128 = ((x120 as u128) + x103);
  let x123: u64 = ((x119 >> 56) as u64);
  let x124: u64 = ((x119 & (0xffffffffffffff as u128)) as u64);
  let x125: u128 = ((x123 as u128) + x106);
  let x126: u64 = ((x122 >> 56) as u64);
  let x127: u64 = ((x122 & (0xffffffffffffff as u128)) as u64);
  let x128: u64 = (x126 + x111);
  let x129: u64 = ((x125 >> 56) as u64);
  let x130: u64 = ((x125 & (0xffffffffffffff as u128)) as u64);
  let x131: u64 = (x129 + x101);
  let x132: u64 = (x128 >> 56);
  let x133: u64 = (x128 & 0xffffffffffffff);
  let x134: u64 = (x131 >> 56);
  let x135: u64 = (x131 & 0xffffffffffffff);
  let x136: u64 = (x114 + x132);
  let x137: u64 = (x118 + x132);
  let x138: u64 = (x134 + x136);
  let x139: fiat_p448_u1 = ((x138 >> 56) as fiat_p448_u1);
  let x140: u64 = (x138 & 0xffffffffffffff);
  let x141: u64 = ((x139 as u64) + x121);
  let x142: fiat_p448_u1 = ((x137 >> 56) as fiat_p448_u1);
  let x143: u64 = (x137 & 0xffffffffffffff);
  let x144: u64 = ((x142 as u64) + x124);
  out1[0] = x143;
  out1[1] = x144;
  out1[2] = x130;
  out1[3] = x135;
  out1[4] = x140;
  out1[5] = x141;
  out1[6] = x127;
  out1[7] = x133;
}