//! Autogenerated: 'src/ExtractionOCaml/solinas_reduction' --lang Rust --inline curve25519_solinas 64 '2^255 - 19' mul square
//! curve description: curve25519_solinas
//! machine_wordsize = 64 (from "64")
//! requested operations: mul, square
//! s-c = 2^255 - [(1, 19)] (from "2^255 - 19")
//!
//! Computed values:
//!

#![allow(unused_parens)]
#![allow(non_camel_case_types)]

/** fiat_curve25519_solinas_u1 represents values of 1 bits, stored in one byte. */
pub type fiat_curve25519_solinas_u1 = u8;
/** fiat_curve25519_solinas_i1 represents values of 1 bits, stored in one byte. */
pub type fiat_curve25519_solinas_i1 = i8;
/** fiat_curve25519_solinas_u2 represents values of 2 bits, stored in one byte. */
pub type fiat_curve25519_solinas_u2 = u8;
/** fiat_curve25519_solinas_i2 represents values of 2 bits, stored in one byte. */
pub type fiat_curve25519_solinas_i2 = i8;

/// The function fiat_curve25519_solinas_addcarryx_u64 is an addition with carry.
///
/// Postconditions:
///   out1 = (arg1 + arg2 + arg3) mod 2^64
///   out2 = ⌊(arg1 + arg2 + arg3) / 2^64⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [0x0 ~> 0x1]
// #[no_mangle]
#[inline]
pub fn fiat_curve25519_solinas_addcarryx_u64(out1: &mut u64, out2: &mut fiat_curve25519_solinas_u1, arg1: fiat_curve25519_solinas_u1, arg2: u64, arg3: u64) {
  let x1: u128 = (((arg1 as u128) + (arg2 as u128)) + (arg3 as u128));
  let x2: u64 = ((x1 & (0xffffffffffffffff as u128)) as u64);
  let x3: fiat_curve25519_solinas_u1 = ((x1 >> 64) as fiat_curve25519_solinas_u1);
  *out1 = x2;
  *out2 = x3;
}
/// The function fiat_curve25519_solinas_mulx_u64 is a multiplication, returning the full double-width result.
///
/// Postconditions:
///   out1 = (arg1 * arg2) mod 2^64
///   out2 = ⌊arg1 * arg2 / 2^64⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0xffffffffffffffff]
///   arg2: [0x0 ~> 0xffffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
///   out2: [0x0 ~> 0xffffffffffffffff]
// #[no_mangle]
#[inline]
pub fn fiat_curve25519_solinas_mulx_u64(out1: &mut u64, out2: &mut u64, arg1: u64, arg2: u64) {
  let x1: u128 = ((arg1 as u128) * (arg2 as u128));
  let x2: u64 = ((x1 & (0xffffffffffffffff as u128)) as u64);
  let x3: u64 = ((x1 >> 64) as u64);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_curve25519_solinas_cmovznz_u64 is a single-word conditional move.
///
/// Postconditions:
///   out1 = (if arg1 = 0 then arg2 else arg3)
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
// #[no_mangle]
#[inline]
pub fn fiat_curve25519_solinas_cmovznz_u64(out1: &mut u64, arg1: fiat_curve25519_solinas_u1, arg2: u64, arg3: u64) {
  let x1: fiat_curve25519_solinas_u1 = (!(!arg1));
  let x2: u64 = ((((((0x0 as fiat_curve25519_solinas_i2) - (x1 as fiat_curve25519_solinas_i2)) as fiat_curve25519_solinas_i1) as i128) & (0xffffffffffffffff as i128)) as u64);
  let x3: u64 = ((x2 & arg3) | ((!x2) & arg2));
  *out1 = x3;
}

/// The function fiat_curve25519_solinas_mul multiplies two field elements.
///
/// Postconditions:
///   eval out1 mod 57896044618658097711785492504343953926634992332820282019728792003956564819949 = (eval arg1 * eval arg2) mod 57896044618658097711785492504343953926634992332820282019728792003956564819949
///
/// Input Bounds:
///   arg1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
///   arg2: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
/// Output Bounds:
///   out1: [[0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff], [0x0 ~> 0xffffffffffffffff]]
#[no_mangle]
#[inline]
pub fn rust_fiat_curve25519_solinas_mul_small_two_carry(out1: &mut [u64; 4], arg1: &[u64; 4], arg2: &[u64; 4]) {
  let mut x1: u64 = 0;
  let mut x2: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x1, &mut x2, (arg1[3]), (arg2[3]));
  let mut x3: u64 = 0;
  let mut x4: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x3, &mut x4, (arg1[3]), (arg2[2]));
  let mut x5: u64 = 0;
  let mut x6: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x5, &mut x6, (arg1[3]), (arg2[1]));
  let mut x7: u64 = 0;
  let mut x8: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x7, &mut x8, (arg1[3]), (arg2[0]));
  let mut x9: u64 = 0;
  let mut x10: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x9, &mut x10, (arg1[2]), (arg2[3]));
  let mut x11: u64 = 0;
  let mut x12: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x11, &mut x12, (arg1[2]), (arg2[2]));
  let mut x13: u64 = 0;
  let mut x14: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x13, &mut x14, (arg1[2]), (arg2[1]));
  let mut x15: u64 = 0;
  let mut x16: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x15, &mut x16, (arg1[2]), (arg2[0]));
  let mut x17: u64 = 0;
  let mut x18: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x17, &mut x18, (arg1[1]), (arg2[3]));
  let mut x19: u64 = 0;
  let mut x20: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x19, &mut x20, (arg1[1]), (arg2[2]));
  let mut x21: u64 = 0;
  let mut x22: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x21, &mut x22, (arg1[1]), (arg2[1]));
  let mut x23: u64 = 0;
  let mut x24: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x23, &mut x24, (arg1[1]), (arg2[0]));
  let mut x25: u64 = 0;
  let mut x26: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x25, &mut x26, (arg1[0]), (arg2[3]));
  let mut x27: u64 = 0;
  let mut x28: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x27, &mut x28, (arg1[0]), (arg2[2]));
  let mut x29: u64 = 0;
  let mut x30: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x29, &mut x30, (arg1[0]), (arg2[1]));
  let mut x31: u64 = 0;
  let mut x32: u64 = 0;
  fiat_curve25519_solinas_mulx_u64(&mut x31, &mut x32, (arg1[0]), (arg2[0]));
  let mut x33: u64 = 0;
  let mut x34: fiat_curve25519_solinas_u1 = 0;
  fiat_curve25519_solinas_addcarryx_u64(&mut x33, &mut x34, 0x0, x28, x7);
  let mut x35: u64 = 0;
  let mut x36: fiat_curve25519_solinas_u1 = 0;
  fiat_curve25519_solinas_addcarryx_u64(&mut x35, &mut x36, x34, x26, x5);
  let x37: u64 = ((x36 as u64) + x18);
  let mut x38: u64 = 0;
  let mut x39: fiat_curve25519_solinas_u1 = 0;
  fiat_curve25519_solinas_addcarryx_u64(&mut x38, &mut x39, 0x0, x33, x13);
  let mut x40: u64 = 0;
  let mut x41: fiat_curve25519_solinas_u1 = 0;
  fiat_curve25519_solinas_addcarryx_u64(&mut x40, &mut x41, x39, x35, x8);
  let mut x42: u64 = 0;
  let mut x43: fiat_curve25519_solinas_u1 = 0;
  fiat_curve25519_solinas_addcarryx_u64(&mut x42, &mut x43, x41, x37, (0x0 as u64));
  let x44: u64 = ((x43 as u64) + x10);
  out1[0] = x37;
  out1[1] = x38;
  out1[2] = x42;
  out1[3] = x44;
}