//! Autogenerated: 'src/ExtractionOCaml/unsaturated_solinas' --lang Rust --inline p448 64 8 '2^448 - 2^224 - 1' carry_mul carry_square carry add sub opp selectznz to_bytes from_bytes relax
//! curve description: p448
//! machine_wordsize = 64 (from "64")
//! requested operations: carry_mul, carry_square, carry, add, sub, opp, selectznz, to_bytes, from_bytes, relax
//! n = 8 (from "8")
//! s-c = 2^448 - [(2^224, 1), (1, 1)] (from "2^448 - 2^224 - 1")
//! tight_bounds_multiplier = 1 (from "")
//!
//! Computed values:
//!   carry_chain = [3, 7, 4, 0, 5, 1, 6, 2, 7, 3, 4, 0]
//!   eval z = z[0] + (z[1] << 56) + (z[2] << 112) + (z[3] << 168) + (z[4] << 224) + (z[5] << 0x118) + (z[6] << 0x150) + (z[7] << 0x188)
//!   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8)
//!   balance = [0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffc, 0x1fffffffffffffe, 0x1fffffffffffffe, 0x1fffffffffffffe]

#![allow(unused_parens)]
#![allow(non_camel_case_types)]

/** fiat_p448_u1 represents values of 1 bits, stored in one byte. */
pub type fiat_p448_u1 = u8;
/** fiat_p448_i1 represents values of 1 bits, stored in one byte. */
pub type fiat_p448_i1 = i8;
/** fiat_p448_u2 represents values of 2 bits, stored in one byte. */
pub type fiat_p448_u2 = u8;
/** fiat_p448_i2 represents values of 2 bits, stored in one byte. */
pub type fiat_p448_i2 = i8;

/** The type fiat_p448_loose_field_element is a field element with loose bounds. */
/** Bounds: [[0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000], [0x0 ~> 0x300000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p448_loose_field_element(pub [u64; 8]);

impl core::ops::Index<usize> for fiat_p448_loose_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p448_loose_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

/** The type fiat_p448_tight_field_element is a field element with tight bounds. */
/** Bounds: [[0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000], [0x0 ~> 0x100000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p448_tight_field_element(pub [u64; 8]);

impl core::ops::Index<usize> for fiat_p448_tight_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p448_tight_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

#[no_mangle]
#[inline]
pub fn rust_fiat_p448_solinas_carry_square(out1: &mut fiat_p448_tight_field_element, arg1: &fiat_p448_loose_field_element) {
  let x1: u64 = (arg1[7]);
  let x2: u64 = (arg1[7]);
  let x3: u64 = (x1 * 0x2);
  let x4: u64 = (x2 * 0x2);
  let x5: u64 = ((arg1[7]) * 0x2);
  let x6: u64 = (arg1[6]);
  let x7: u64 = (arg1[6]);
  let x8: u64 = (x6 * 0x2);
  let x9: u64 = (x7 * 0x2);
  let x10: u64 = ((arg1[6]) * 0x2);
  let x11: u64 = (arg1[5]);
  let x12: u64 = (arg1[5]);
  let x13: u64 = (x11 * 0x2);
  let x14: u64 = (x12 * 0x2);
  let x15: u64 = ((arg1[5]) * 0x2);
  let x16: u64 = (arg1[4]);
  let x17: u64 = (arg1[4]);
  let x18: u64 = ((arg1[4]) * 0x2);
  let x19: u64 = ((arg1[3]) * 0x2);
  let x20: u64 = ((arg1[2]) * 0x2);
  let x21: u64 = ((arg1[1]) * 0x2);
  let x22: u128 = (((arg1[7]) as u128) * (x1 as u128));
  let x23: u128 = (((arg1[6]) as u128) * (x3 as u128));
  let x24: u128 = (((arg1[6]) as u128) * (x6 as u128));
  let x25: u128 = (((arg1[5]) as u128) * (x3 as u128));
  let x26: u128 = (((arg1[7]) as u128) * (x1 as u128));
  let x27: u128 = (((arg1[6]) as u128) * (x3 as u128));
  let x28: u128 = (((arg1[6]) as u128) * (x6 as u128));
  let x29: u128 = (((arg1[5]) as u128) * (x3 as u128));
  let x30: u128 = (((arg1[7]) as u128) * (x2 as u128));
  let x31: u128 = (((arg1[6]) as u128) * (x4 as u128));
  let x32: u128 = (((arg1[6]) as u128) * (x7 as u128));
  let x33: u128 = (((arg1[5]) as u128) * (x4 as u128));
  let x34: u128 = (((arg1[5]) as u128) * (x9 as u128));
  let x35: u128 = (((arg1[5]) as u128) * (x8 as u128));
  let x36: u128 = (((arg1[5]) as u128) * (x12 as u128));
  let x37: u128 = (((arg1[5]) as u128) * (x11 as u128));
  let x38: u128 = (((arg1[4]) as u128) * (x4 as u128));
  let x39: u128 = (((arg1[4]) as u128) * (x3 as u128));
  let x40: u128 = (((arg1[4]) as u128) * (x9 as u128));
  let x41: u128 = (((arg1[4]) as u128) * (x8 as u128));
  let x42: u128 = (((arg1[4]) as u128) * (x14 as u128));
  let x43: u128 = (((arg1[4]) as u128) * (x13 as u128));
  let x44: u128 = (((arg1[4]) as u128) * (x17 as u128));
  let x45: u128 = (((arg1[4]) as u128) * (x16 as u128));
  let x46: u128 = (((arg1[3]) as u128) * (x4 as u128));
  let x47: u128 = (((arg1[3]) as u128) * (x3 as u128));
  let x48: u128 = (((arg1[3]) as u128) * (x9 as u128));
  let x49: u128 = (((arg1[3]) as u128) * (x8 as u128));
  let x50: u128 = (((arg1[3]) as u128) * (x14 as u128));
  let x51: u128 = (((arg1[3]) as u128) * (x13 as u128));
  let x52: u128 = (((arg1[3]) as u128) * (x18 as u128));
  let x53: u128 = (((arg1[3]) as u128) * ((arg1[3]) as u128));
  let x54: u128 = (((arg1[2]) as u128) * (x4 as u128));
  let x55: u128 = (((arg1[2]) as u128) * (x3 as u128));
  let x56: u128 = (((arg1[2]) as u128) * (x9 as u128));
  let x57: u128 = (((arg1[2]) as u128) * (x8 as u128));
  let x58: u128 = (((arg1[2]) as u128) * (x15 as u128));
  let x59: u128 = (((arg1[2]) as u128) * (x18 as u128));
  let x60: u128 = (((arg1[2]) as u128) * (x19 as u128));
  let x61: u128 = (((arg1[2]) as u128) * ((arg1[2]) as u128));
  let x62: u128 = (((arg1[1]) as u128) * (x4 as u128));
  let x63: u128 = (((arg1[1]) as u128) * (x3 as u128));
  let x64: u128 = (((arg1[1]) as u128) * (x10 as u128));
  let x65: u128 = (((arg1[1]) as u128) * (x15 as u128));
  let x66: u128 = (((arg1[1]) as u128) * (x18 as u128));
  let x67: u128 = (((arg1[1]) as u128) * (x19 as u128));
  let x68: u128 = (((arg1[1]) as u128) * (x20 as u128));
  let x69: u128 = (((arg1[1]) as u128) * ((arg1[1]) as u128));
  let x70: u128 = (((arg1[0]) as u128) * (x5 as u128));
  let x71: u128 = (((arg1[0]) as u128) * (x10 as u128));
  let x72: u128 = (((arg1[0]) as u128) * (x15 as u128));
  let x73: u128 = (((arg1[0]) as u128) * (x18 as u128));
  let x74: u128 = (((arg1[0]) as u128) * (x19 as u128));
  let x75: u128 = (((arg1[0]) as u128) * (x20 as u128));
  let x76: u128 = (((arg1[0]) as u128) * (x21 as u128));
  let x77: u128 = (((arg1[0]) as u128) * ((arg1[0]) as u128));
  let x78: u128 = (x74 + (x68 + (x38 + x34)));
  let x79: u64 = ((x78 >> 56) as u64);
  let x80: u64 = ((x78 & (0xffffffffffffff as u128)) as u64);
  let x81: u128 = (x70 + (x64 + (x58 + (x52 + (x39 + x35)))));
  let x82: u128 = (x71 + (x65 + (x59 + (x53 + (x47 + (x41 + (x37 + (x30 + x26))))))));
  let x83: u128 = (x72 + (x66 + (x60 + (x55 + (x49 + (x43 + (x31 + x27)))))));
  let x84: u128 = (x73 + (x67 + (x63 + (x61 + (x57 + (x51 + (x45 + (x33 + (x32 + (x29 + x28))))))))));
  let x85: u128 = (x75 + (x69 + (x46 + (x40 + (x36 + x22)))));
  let x86: u128 = (x76 + (x54 + (x48 + (x42 + x23))));
  let x87: u128 = (x77 + (x62 + (x56 + (x50 + (x44 + (x25 + x24))))));
  let x88: u128 = ((x79 as u128) + x84);
  let x89: u64 = ((x81 >> 56) as u64);
  let x90: u64 = ((x81 & (0xffffffffffffff as u128)) as u64);
  let x91: u128 = (x88 + (x89 as u128));
  let x92: u64 = ((x91 >> 56) as u64);
  let x93: u64 = ((x91 & (0xffffffffffffff as u128)) as u64);
  let x94: u128 = (x87 + (x89 as u128));
  let x95: u128 = ((x92 as u128) + x83);
  let x96: u64 = ((x94 >> 56) as u64);
  let x97: u64 = ((x94 & (0xffffffffffffff as u128)) as u64);
  let x98: u128 = ((x96 as u128) + x86);
  let x99: u64 = ((x95 >> 56) as u64);
  let x100: u64 = ((x95 & (0xffffffffffffff as u128)) as u64);
  let x101: u128 = ((x99 as u128) + x82);
  let x102: u64 = ((x98 >> 56) as u64);
  let x103: u64 = ((x98 & (0xffffffffffffff as u128)) as u64);
  let x104: u128 = ((x102 as u128) + x85);
  let x105: u64 = ((x101 >> 56) as u64);
  let x106: u64 = ((x101 & (0xffffffffffffff as u128)) as u64);
  let x107: u64 = (x105 + x90);
  let x108: u64 = ((x104 >> 56) as u64);
  let x109: u64 = ((x104 & (0xffffffffffffff as u128)) as u64);
  let x110: u64 = (x108 + x80);
  let x111: u64 = (x107 >> 56);
  let x112: u64 = (x107 & 0xffffffffffffff);
  let x113: u64 = (x110 >> 56);
  let x114: u64 = (x110 & 0xffffffffffffff);
  let x115: u64 = (x93 + x111);
  let x116: u64 = (x97 + x111);
  let x117: u64 = (x113 + x115);
  let x118: fiat_p448_u1 = ((x117 >> 56) as fiat_p448_u1);
  let x119: u64 = (x117 & 0xffffffffffffff);
  let x120: u64 = ((x118 as u64) + x100);
  let x121: fiat_p448_u1 = ((x116 >> 56) as fiat_p448_u1);
  let x122: u64 = (x116 & 0xffffffffffffff);
  let x123: u64 = ((x121 as u64) + x103);
  out1[0] = x122;
  out1[1] = x123;
  out1[2] = x109;
  out1[3] = x114;
  out1[4] = x119;
  out1[5] = x120;
  out1[6] = x106;
  out1[7] = x112;
}

