//! Autogenerated: 'src/ExtractionOCaml/unsaturated_solinas' --lang Rust --inline p521 64 '(auto)' '2^521 - 1' carry_mul carry_square carry add sub opp selectznz to_bytes from_bytes relax
//! curve description: p521
//! machine_wordsize = 64 (from "64")
//! requested operations: carry_mul, carry_square, carry, add, sub, opp, selectznz, to_bytes, from_bytes, relax
//! n = 9 (from "(auto)")
//! s-c = 2^521 - [(1, 1)] (from "2^521 - 1")
//! tight_bounds_multiplier = 1 (from "")
//!
//! Computed values:
//!   carry_chain = [0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1]
//!   eval z = z[0] + (z[1] << 58) + (z[2] << 116) + (z[3] << 174) + (z[4] << 232) + (z[5] << 0x122) + (z[6] << 0x15c) + (z[7] << 0x196) + (z[8] << 0x1d0)
//!   bytes_eval z = z[0] + (z[1] << 8) + (z[2] << 16) + (z[3] << 24) + (z[4] << 32) + (z[5] << 40) + (z[6] << 48) + (z[7] << 56) + (z[8] << 64) + (z[9] << 72) + (z[10] << 80) + (z[11] << 88) + (z[12] << 96) + (z[13] << 104) + (z[14] << 112) + (z[15] << 120) + (z[16] << 128) + (z[17] << 136) + (z[18] << 144) + (z[19] << 152) + (z[20] << 160) + (z[21] << 168) + (z[22] << 176) + (z[23] << 184) + (z[24] << 192) + (z[25] << 200) + (z[26] << 208) + (z[27] << 216) + (z[28] << 224) + (z[29] << 232) + (z[30] << 240) + (z[31] << 248) + (z[32] << 256) + (z[33] << 0x108) + (z[34] << 0x110) + (z[35] << 0x118) + (z[36] << 0x120) + (z[37] << 0x128) + (z[38] << 0x130) + (z[39] << 0x138) + (z[40] << 0x140) + (z[41] << 0x148) + (z[42] << 0x150) + (z[43] << 0x158) + (z[44] << 0x160) + (z[45] << 0x168) + (z[46] << 0x170) + (z[47] << 0x178) + (z[48] << 0x180) + (z[49] << 0x188) + (z[50] << 0x190) + (z[51] << 0x198) + (z[52] << 0x1a0) + (z[53] << 0x1a8) + (z[54] << 0x1b0) + (z[55] << 0x1b8) + (z[56] << 0x1c0) + (z[57] << 0x1c8) + (z[58] << 0x1d0) + (z[59] << 0x1d8) + (z[60] << 0x1e0) + (z[61] << 0x1e8) + (z[62] << 0x1f0) + (z[63] << 0x1f8) + (z[64] << 2^9) + (z[65] << 0x208)
//!   balance = [0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x7fffffffffffffe, 0x3fffffffffffffe]

#![allow(unused_parens)]
#![allow(non_camel_case_types)]

/** fiat_p521_u1 represents values of 1 bits, stored in one byte. */
pub type fiat_p521_u1 = u8;
/** fiat_p521_i1 represents values of 1 bits, stored in one byte. */
pub type fiat_p521_i1 = i8;
/** fiat_p521_u2 represents values of 2 bits, stored in one byte. */
pub type fiat_p521_u2 = u8;
/** fiat_p521_i2 represents values of 2 bits, stored in one byte. */
pub type fiat_p521_i2 = i8;

/** The type fiat_p521_loose_field_element is a field element with loose bounds. */
/** Bounds: [[0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0xc00000000000000], [0x0 ~> 0x600000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p521_loose_field_element(pub [u64; 9]);

impl core::ops::Index<usize> for fiat_p521_loose_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p521_loose_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

/** The type fiat_p521_tight_field_element is a field element with tight bounds. */
/** Bounds: [[0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x400000000000000], [0x0 ~> 0x200000000000000]] */
#[derive(Clone, Copy)]
pub struct fiat_p521_tight_field_element(pub [u64; 9]);

impl core::ops::Index<usize> for fiat_p521_tight_field_element {
    type Output = u64;
    #[inline]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl core::ops::IndexMut<usize> for fiat_p521_tight_field_element {
    #[inline]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}


/// The function fiat_p521_addcarryx_u58 is an addition with carry.
///
/// Postconditions:
///   out1 = (arg1 + arg2 + arg3) mod 2^58
///   out2 = ⌊(arg1 + arg2 + arg3) / 2^58⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0x3ffffffffffffff]
///   arg3: [0x0 ~> 0x3ffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0x3ffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p521_addcarryx_u58(out1: &mut u64, out2: &mut fiat_p521_u1, arg1: fiat_p521_u1, arg2: u64, arg3: u64) {
  let x1: u64 = (((arg1 as u64) + arg2) + arg3);
  let x2: u64 = (x1 & 0x3ffffffffffffff);
  let x3: fiat_p521_u1 = ((x1 >> 58) as fiat_p521_u1);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_p521_subborrowx_u58 is a subtraction with borrow.
///
/// Postconditions:
///   out1 = (-arg1 + arg2 + -arg3) mod 2^58
///   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^58⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0x3ffffffffffffff]
///   arg3: [0x0 ~> 0x3ffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0x3ffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p521_subborrowx_u58(out1: &mut u64, out2: &mut fiat_p521_u1, arg1: fiat_p521_u1, arg2: u64, arg3: u64) {
  let x1: i64 = ((((((arg2 as i128) - (arg1 as i128)) as i64) as i128) - (arg3 as i128)) as i64);
  let x2: fiat_p521_i1 = ((x1 >> 58) as fiat_p521_i1);
  let x3: u64 = (((x1 as i128) & (0x3ffffffffffffff as i128)) as u64);
  *out1 = x3;
  *out2 = (((0x0 as fiat_p521_i2) - (x2 as fiat_p521_i2)) as fiat_p521_u1);
}

/// The function fiat_p521_addcarryx_u57 is an addition with carry.
///
/// Postconditions:
///   out1 = (arg1 + arg2 + arg3) mod 2^57
///   out2 = ⌊(arg1 + arg2 + arg3) / 2^57⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0x1ffffffffffffff]
///   arg3: [0x0 ~> 0x1ffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0x1ffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p521_addcarryx_u57(out1: &mut u64, out2: &mut fiat_p521_u1, arg1: fiat_p521_u1, arg2: u64, arg3: u64) {
  let x1: u64 = (((arg1 as u64) + arg2) + arg3);
  let x2: u64 = (x1 & 0x1ffffffffffffff);
  let x3: fiat_p521_u1 = ((x1 >> 57) as fiat_p521_u1);
  *out1 = x2;
  *out2 = x3;
}

/// The function fiat_p521_subborrowx_u57 is a subtraction with borrow.
///
/// Postconditions:
///   out1 = (-arg1 + arg2 + -arg3) mod 2^57
///   out2 = -⌊(-arg1 + arg2 + -arg3) / 2^57⌋
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0x1ffffffffffffff]
///   arg3: [0x0 ~> 0x1ffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0x1ffffffffffffff]
///   out2: [0x0 ~> 0x1]
#[inline]
pub fn fiat_p521_subborrowx_u57(out1: &mut u64, out2: &mut fiat_p521_u1, arg1: fiat_p521_u1, arg2: u64, arg3: u64) {
  let x1: i64 = ((((((arg2 as i128) - (arg1 as i128)) as i64) as i128) - (arg3 as i128)) as i64);
  let x2: fiat_p521_i1 = ((x1 >> 57) as fiat_p521_i1);
  let x3: u64 = (((x1 as i128) & (0x1ffffffffffffff as i128)) as u64);
  *out1 = x3;
  *out2 = (((0x0 as fiat_p521_i2) - (x2 as fiat_p521_i2)) as fiat_p521_u1);
}

/// The function fiat_p521_cmovznz_u64 is a single-word conditional move.
///
/// Postconditions:
///   out1 = (if arg1 = 0 then arg2 else arg3)
///
/// Input Bounds:
///   arg1: [0x0 ~> 0x1]
///   arg2: [0x0 ~> 0xffffffffffffffff]
///   arg3: [0x0 ~> 0xffffffffffffffff]
/// Output Bounds:
///   out1: [0x0 ~> 0xffffffffffffffff]
#[inline]
pub fn fiat_p521_cmovznz_u64(out1: &mut u64, arg1: fiat_p521_u1, arg2: u64, arg3: u64) {
  let x1: fiat_p521_u1 = (!(!arg1));
  let x2: u64 = ((((((0x0 as fiat_p521_i2) - (x1 as fiat_p521_i2)) as fiat_p521_i1) as i128) & (0xffffffffffffffff as i128)) as u64);
  let x3: u64 = ((x2 & arg3) | ((!x2) & arg2));
  *out1 = x3;
}

/// The function fiat_p521_carry_mul multiplies two field elements and reduces the result.
///
/// Postconditions:
///   eval out1 mod m = (eval arg1 * eval arg2) mod m
///
#[no_mangle]
#[inline]
pub fn rust_fiat_p521_carry_mul(out1: &mut fiat_p521_tight_field_element, arg1: &fiat_p521_loose_field_element, arg2: &fiat_p521_loose_field_element) {
  let x1: u128 = (((arg1[8]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x2: u128 = (((arg1[8]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x3: u128 = (((arg1[8]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x4: u128 = (((arg1[8]) as u128) * (((arg2[5]) * 0x2) as u128));
  let x5: u128 = (((arg1[8]) as u128) * (((arg2[4]) * 0x2) as u128));
  let x6: u128 = (((arg1[8]) as u128) * (((arg2[3]) * 0x2) as u128));
  let x7: u128 = (((arg1[8]) as u128) * (((arg2[2]) * 0x2) as u128));
  let x8: u128 = (((arg1[8]) as u128) * (((arg2[1]) * 0x2) as u128));
  let x9: u128 = (((arg1[7]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x10: u128 = (((arg1[7]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x11: u128 = (((arg1[7]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x12: u128 = (((arg1[7]) as u128) * (((arg2[5]) * 0x2) as u128));
  let x13: u128 = (((arg1[7]) as u128) * (((arg2[4]) * 0x2) as u128));
  let x14: u128 = (((arg1[7]) as u128) * (((arg2[3]) * 0x2) as u128));
  let x15: u128 = (((arg1[7]) as u128) * (((arg2[2]) * 0x2) as u128));
  let x16: u128 = (((arg1[6]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x17: u128 = (((arg1[6]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x18: u128 = (((arg1[6]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x19: u128 = (((arg1[6]) as u128) * (((arg2[5]) * 0x2) as u128));
  let x20: u128 = (((arg1[6]) as u128) * (((arg2[4]) * 0x2) as u128));
  let x21: u128 = (((arg1[6]) as u128) * (((arg2[3]) * 0x2) as u128));
  let x22: u128 = (((arg1[5]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x23: u128 = (((arg1[5]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x24: u128 = (((arg1[5]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x25: u128 = (((arg1[5]) as u128) * (((arg2[5]) * 0x2) as u128));
  let x26: u128 = (((arg1[5]) as u128) * (((arg2[4]) * 0x2) as u128));
  let x27: u128 = (((arg1[4]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x28: u128 = (((arg1[4]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x29: u128 = (((arg1[4]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x30: u128 = (((arg1[4]) as u128) * (((arg2[5]) * 0x2) as u128));
  let x31: u128 = (((arg1[3]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x32: u128 = (((arg1[3]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x33: u128 = (((arg1[3]) as u128) * (((arg2[6]) * 0x2) as u128));
  let x34: u128 = (((arg1[2]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x35: u128 = (((arg1[2]) as u128) * (((arg2[7]) * 0x2) as u128));
  let x36: u128 = (((arg1[1]) as u128) * (((arg2[8]) * 0x2) as u128));
  let x37: u128 = (((arg1[8]) as u128) * ((arg2[0]) as u128));
  let x38: u128 = (((arg1[7]) as u128) * ((arg2[1]) as u128));
  let x39: u128 = (((arg1[7]) as u128) * ((arg2[0]) as u128));
  let x40: u128 = (((arg1[6]) as u128) * ((arg2[2]) as u128));
  let x41: u128 = (((arg1[6]) as u128) * ((arg2[1]) as u128));
  let x42: u128 = (((arg1[6]) as u128) * ((arg2[0]) as u128));
  let x43: u128 = (((arg1[5]) as u128) * ((arg2[3]) as u128));
  let x44: u128 = (((arg1[5]) as u128) * ((arg2[2]) as u128));
  let x45: u128 = (((arg1[5]) as u128) * ((arg2[1]) as u128));
  let x46: u128 = (((arg1[5]) as u128) * ((arg2[0]) as u128));
  let x47: u128 = (((arg1[4]) as u128) * ((arg2[4]) as u128));
  let x48: u128 = (((arg1[4]) as u128) * ((arg2[3]) as u128));
  let x49: u128 = (((arg1[4]) as u128) * ((arg2[2]) as u128));
  let x50: u128 = (((arg1[4]) as u128) * ((arg2[1]) as u128));
  let x51: u128 = (((arg1[4]) as u128) * ((arg2[0]) as u128));
  let x52: u128 = (((arg1[3]) as u128) * ((arg2[5]) as u128));
  let x53: u128 = (((arg1[3]) as u128) * ((arg2[4]) as u128));
  let x54: u128 = (((arg1[3]) as u128) * ((arg2[3]) as u128));
  let x55: u128 = (((arg1[3]) as u128) * ((arg2[2]) as u128));
  let x56: u128 = (((arg1[3]) as u128) * ((arg2[1]) as u128));
  let x57: u128 = (((arg1[3]) as u128) * ((arg2[0]) as u128));
  let x58: u128 = (((arg1[2]) as u128) * ((arg2[6]) as u128));
  let x59: u128 = (((arg1[2]) as u128) * ((arg2[5]) as u128));
  let x60: u128 = (((arg1[2]) as u128) * ((arg2[4]) as u128));
  let x61: u128 = (((arg1[2]) as u128) * ((arg2[3]) as u128));
  let x62: u128 = (((arg1[2]) as u128) * ((arg2[2]) as u128));
  let x63: u128 = (((arg1[2]) as u128) * ((arg2[1]) as u128));
  let x64: u128 = (((arg1[2]) as u128) * ((arg2[0]) as u128));
  let x65: u128 = (((arg1[1]) as u128) * ((arg2[7]) as u128));
  let x66: u128 = (((arg1[1]) as u128) * ((arg2[6]) as u128));
  let x67: u128 = (((arg1[1]) as u128) * ((arg2[5]) as u128));
  let x68: u128 = (((arg1[1]) as u128) * ((arg2[4]) as u128));
  let x69: u128 = (((arg1[1]) as u128) * ((arg2[3]) as u128));
  let x70: u128 = (((arg1[1]) as u128) * ((arg2[2]) as u128));
  let x71: u128 = (((arg1[1]) as u128) * ((arg2[1]) as u128));
  let x72: u128 = (((arg1[1]) as u128) * ((arg2[0]) as u128));
  let x73: u128 = (((arg1[0]) as u128) * ((arg2[8]) as u128));
  let x74: u128 = (((arg1[0]) as u128) * ((arg2[7]) as u128));
  let x75: u128 = (((arg1[0]) as u128) * ((arg2[6]) as u128));
  let x76: u128 = (((arg1[0]) as u128) * ((arg2[5]) as u128));
  let x77: u128 = (((arg1[0]) as u128) * ((arg2[4]) as u128));
  let x78: u128 = (((arg1[0]) as u128) * ((arg2[3]) as u128));
  let x79: u128 = (((arg1[0]) as u128) * ((arg2[2]) as u128));
  let x80: u128 = (((arg1[0]) as u128) * ((arg2[1]) as u128));
  let x81: u128 = (((arg1[0]) as u128) * ((arg2[0]) as u128));
  let x82: u128 = (x81 + (x36 + (x35 + (x33 + (x30 + (x26 + (x21 + (x15 + x8))))))));
  let x83: u128 = (x82 >> 58);
  let x84: u64 = ((x82 & (0x3ffffffffffffff as u128)) as u64);
  let x85: u128 = (x73 + (x65 + (x58 + (x52 + (x47 + (x43 + (x40 + (x38 + x37))))))));
  let x86: u128 = (x74 + (x66 + (x59 + (x53 + (x48 + (x44 + (x41 + (x39 + x1))))))));
  let x87: u128 = (x75 + (x67 + (x60 + (x54 + (x49 + (x45 + (x42 + (x9 + x2))))))));
  let x88: u128 = (x76 + (x68 + (x61 + (x55 + (x50 + (x46 + (x16 + (x10 + x3))))))));
  let x89: u128 = (x77 + (x69 + (x62 + (x56 + (x51 + (x22 + (x17 + (x11 + x4))))))));
  let x90: u128 = (x78 + (x70 + (x63 + (x57 + (x27 + (x23 + (x18 + (x12 + x5))))))));
  let x91: u128 = (x79 + (x71 + (x64 + (x31 + (x28 + (x24 + (x19 + (x13 + x6))))))));
  let x92: u128 = (x80 + (x72 + (x34 + (x32 + (x29 + (x25 + (x20 + (x14 + x7))))))));
  let x93: u128 = (x83 + x92);
  let x94: u128 = (x93 >> 58);
  let x95: u64 = ((x93 & (0x3ffffffffffffff as u128)) as u64);
  let x96: u128 = (x94 + x91);
  let x97: u128 = (x96 >> 58);
  let x98: u64 = ((x96 & (0x3ffffffffffffff as u128)) as u64);
  let x99: u128 = (x97 + x90);
  let x100: u128 = (x99 >> 58);
  let x101: u64 = ((x99 & (0x3ffffffffffffff as u128)) as u64);
  let x102: u128 = (x100 + x89);
  let x103: u128 = (x102 >> 58);
  let x104: u64 = ((x102 & (0x3ffffffffffffff as u128)) as u64);
  let x105: u128 = (x103 + x88);
  let x106: u128 = (x105 >> 58);
  let x107: u64 = ((x105 & (0x3ffffffffffffff as u128)) as u64);
  let x108: u128 = (x106 + x87);
  let x109: u128 = (x108 >> 58);
  let x110: u64 = ((x108 & (0x3ffffffffffffff as u128)) as u64);
  let x111: u128 = (x109 + x86);
  let x112: u128 = (x111 >> 58);
  let x113: u64 = ((x111 & (0x3ffffffffffffff as u128)) as u64);
  let x114: u128 = (x112 + x85);
  let x115: u128 = (x114 >> 57);
  let x116: u64 = ((x114 & (0x1ffffffffffffff as u128)) as u64);
  let x117: u128 = ((x84 as u128) + x115);
  let x118: u64 = ((x117 >> 58) as u64);
  let x119: u64 = ((x117 & (0x3ffffffffffffff as u128)) as u64);
  let x120: u64 = (x118 + x95);
  let x121: fiat_p521_u1 = ((x120 >> 58) as fiat_p521_u1);
  let x122: u64 = (x120 & 0x3ffffffffffffff);
  let x123: u64 = ((x121 as u64) + x98);
  out1[0] = x119;
  out1[1] = x122;
  out1[2] = x123;
  out1[3] = x101;
  out1[4] = x104;
  out1[5] = x107;
  out1[6] = x110;
  out1[7] = x113;
  out1[8] = x116;
}